# Generated by Django 3.1.7 on 2021-03-17 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodel',
            old_name='mdemo',
            new_name='memo',
        ),
    ]
